export const aboutData = {
  "our-story": {
    title: "Our Story",
    subtitle: "A Journey of Innovation & Excellence",
    description: "Founded with a vision to transform how businesses leverage technology, Netwit has grown from a small startup to a global technology solutions provider. Our journey is marked by continuous innovation, client success, and a commitment to excellence.",
    stats: [
      { value: "25+", label: "Years of Excellence" },
      { value: "2000+", label: "Clients Worldwide" },
      { value: "1500+", label: "Team Members" },
      { value: "50+", label: "Countries Served" },
    ],
    highlights: [
      "Started as a small tech consultancy",
      "Expanded to 10+ global locations",
      "Built 2000+ successful projects",
      "Earned industry-leading certifications",
    ],
  },
  "25-years-excellence": {
    title: "25+ Years of Excellence",
    subtitle: "Quarter Century of Innovation",
    description: "For over 25 years, Netwit has been at the forefront of technology innovation. Our longevity is a testament to our commitment to quality, customer satisfaction, and continuous improvement.",
    stats: [
      { value: "25+", label: "Years in Business" },
      { value: "2000+", label: "Projects Delivered" },
      { value: "99%", label: "Client Satisfaction" },
      { value: "24/7", label: "Support Available" },
    ],
    highlights: [
      "Pioneer in enterprise DevOps",
      "Early adopter of cloud computing",
      "Leader in AI/ML integration",
      "Trusted by Fortune 500 companies",
    ],
  },
  "why-netsmartz": {
    title: "Why Netwit",
    subtitle: "Your Partner in Digital Transformation",
    description: "At Netwit, we don't just provide technology solutions – we become your strategic partner in digital transformation. Our commitment to excellence, innovation, and client success sets us apart.",
    stats: [
      { value: "1500+", label: "Expert Engineers" },
      { value: "2000+", label: "Successful Projects" },
      { value: "50+", label: "Technology Partners" },
      { value: "24/7", label: "Support Coverage" },
    ],
    highlights: [
      "AI-first approach to solutions",
      "Agile methodology",
      "Transparent communication",
      "Proven track record",
    ],
  },
  timeline: {
    title: "Timeline",
    subtitle: "Our Journey Through the Years",
    description: "Explore the key milestones that have shaped Netwit into what we are today. From our humble beginnings to becoming a global technology leader.",
    stats: [
      { value: "1999", label: "Founded" },
      { value: "2010", label: "Global Expansion" },
      { value: "2018", label: "AI Division Launch" },
      { value: "2024", label: "50+ Countries" },
    ],
    highlights: [
      "Founded in 1999",
      "First international office in 2010",
      "Launched AI division in 2018",
      "Reached 50+ country presence in 2024",
    ],
  },
  "leadership-team": {
    title: "Leadership Team",
    subtitle: "Meet Our Visionaries",
    description: "Our leadership team brings decades of experience in technology, business strategy, and innovation. They guide our mission to deliver excellence in every project we undertake.",
    stats: [
      { value: "15+", label: "Executive Leaders" },
      { value: "100+", label: "Years Combined Experience" },
      { value: "50+", label: "Industry Awards" },
      { value: "10+", label: "Ph.D. Holders" },
    ],
    highlights: [
      "Industry veterans from top tech companies",
      "Diverse global perspectives",
      "Customer-centric approach",
      "Commitment to innovation",
    ],
  },
  "life-at-netsmartz": {
    title: "Life at Netwit",
    subtitle: "Where Innovation Meets Culture",
    description: "At Netwit, we believe that great work happens in an environment that nurtures creativity, collaboration, and well-being. Our culture is built on trust, transparency, and continuous learning.",
    stats: [
      { value: "1500+", label: "Team Members" },
      { value: "10+", label: "Global Offices" },
      { value: "95%", label: "Employee Retention" },
      { value: "4.5+", label: "Glassdoor Rating" },
    ],
    highlights: [
      "Flexible work arrangements",
      "Continuous learning opportunities",
      "Inclusive workplace culture",
      "Work-life balance initiatives",
    ],
  },
  "netsmartz-academy": {
    title: "Netwit Academy",
    subtitle: "Building Future Tech Leaders",
    description: "Netwit Academy is our commitment to nurturing the next generation of tech talent. Through comprehensive training programs, mentorship, and hands-on projects, we develop industry-ready professionals.",
    stats: [
      { value: "5000+", label: "Graduates" },
      { value: "100+", label: "Training Programs" },
      { value: "90%", label: "Placement Rate" },
      { value: "50+", label: "Corporate Partners" },
    ],
    highlights: [
      "Industry-recognized certifications",
      "Hands-on project experience",
      "Expert mentors",
      "Career placement support",
    ],
  },
  "learning-development": {
    title: "Learning & Development",
    subtitle: "Continuous Growth for All",
    description: "We invest heavily in our people's growth through continuous learning opportunities. From technical skills to leadership development, Netwit ensures every team member has the resources to thrive.",
    stats: [
      { value: "200+", label: "Training Hours/Year" },
      { value: "100%", label: "Team Access" },
      { value: "50+", label: "Certification Programs" },
      { value: "24/7", label: "Learning Platform" },
    ],
    highlights: [
      "Personalized learning paths",
      "Industry certifications",
      "Leadership programs",
      "Technical bootcamps",
    ],
  },
  "ai-first-culture": {
    title: "AI-First Culture",
    subtitle: "Innovation Driven by Intelligence",
    description: "At Netwit, AI is not just a service – it's embedded in our DNA. Our AI-first culture means every solution we deliver leverages the latest in artificial intelligence and machine learning.",
    stats: [
      { value: "200+", label: "AI Engineers" },
      { value: "100+", label: "AI Projects" },
      { value: "50+", label: "AI Solutions" },
      { value: "99%", label: "Client Satisfaction" },
    ],
    highlights: [
      "AI-powered DevOps",
      "Predictive analytics",
      "Intelligent automation",
      "Custom ML models",
    ],
  },
  sustainability: {
    title: "Sustainability",
    subtitle: "Technology for a Greener Future",
    description: "Netwit is committed to sustainable technology practices. We help our clients reduce their carbon footprint through energy-efficient cloud solutions, green computing initiatives, and sustainable IT practices.",
    stats: [
      { value: "40%", label: "Carbon Reduction" },
      { value: "100%", label: "Green Energy Offices" },
      { value: "50+", label: "Green Projects" },
      { value: "ISO", label: "14001 Certified" },
    ],
    highlights: [
      "Green cloud computing",
      "Energy-efficient data centers",
      "Sustainable software development",
      "Carbon footprint tracking",
    ],
  },
  "talent-stories": {
    title: "Talent Stories",
    subtitle: "Voices of Our People",
    description: "Hear from the talented individuals who make Netwit great. Our talent stories showcase the diverse perspectives, achievements, and growth journeys of our team members.",
    stats: [
      { value: "1500+", label: "Team Members" },
      { value: "50+", label: "Countries" },
      { value: "100+", label: "Career Paths" },
      { value: "95%", label: "Employee NPS" },
    ],
    highlights: [
      "Employee testimonials",
      "Career growth stories",
      "Innovation spotlight",
      "Team achievements",
    ],
  },
  "gpw-journal": {
    title: "The GPW Journal",
    subtitle: "Insights for the Modern Enterprise",
    description: "The GPW Journal is our thought leadership publication featuring insights on technology trends, business strategies, and industry best practices from our experts.",
    stats: [
      { value: "100+", label: "Articles Published" },
      { value: "50K+", label: "Monthly Readers" },
      { value: "20+", label: "Industry Contributors" },
      { value: "Weekly", label: "New Content" },
    ],
    highlights: [
      "Technology insights",
      "Business strategies",
      "Industry trends",
      "Expert opinions",
    ],
  },
  events: {
    title: "Events",
    subtitle: "Connect, Learn, Innovate",
    description: "Netwit hosts and participates in events worldwide, bringing together industry leaders, technology experts, and innovators to share knowledge and shape the future.",
    stats: [
      { value: "100+", label: "Events/Year" },
      { value: "10K+", label: "Attendees" },
      { value: "50+", label: "Countries" },
      { value: "Weekly", label: "Webinars" },
    ],
    highlights: [
      "Annual tech conferences",
      "Industry webinars",
      "Community meetups",
      "Partner events",
    ],
  },
  "we-are-hiring": {
    title: "We're Hiring",
    subtitle: "Join Our Global Team",
    description: "Netwit is always looking for talented individuals to join our team. Explore exciting career opportunities and become part of a company that values innovation, growth, and excellence.",
    stats: [
      { value: "200+", label: "Open Positions" },
      { value: "50+", label: "Countries" },
      { value: "Remote", label: "Work Options" },
      { value: "100%", label: "Remote Friendly" },
    ],
    highlights: [
      "Competitive salaries",
      "Health benefits",
      "Learning opportunities",
      "Work-life balance",
    ],
  },
  "giving-back": {
    title: "Giving Back",
    subtitle: "Making a Difference",
    description: "Netwit is committed to making a positive impact in our communities. Through our corporate social responsibility initiatives, we support education, environment, and social causes.",
    stats: [
      { value: "$1M+", label: "Charity Donated" },
      { value: "100+", label: "Charity Partners" },
      { value: "1000+", label: "Volunteer Hours" },
      { value: "50+", label: "Schools Supported" },
    ],
    highlights: [
      "Education scholarships",
      "Environmental initiatives",
      "Community support",
      "Tech for good",
    ],
  },
  "referral-partners": {
    title: "Referral Partners",
    subtitle: "Grow With Us",
    description: "Join our referral partner program and earn rewards for introducing clients to Netwit. It's a win-win opportunity for individuals and businesses to benefit from our success.",
    stats: [
      { value: "500+", label: "Active Partners" },
      { value: "30%", label: "Commission Rate" },
      { value: "$1M+", label: "Partner Earnings" },
      { value: "24/7", label: "Partner Support" },
    ],
    highlights: [
      "Generous commissions",
      "Dedicated support",
      "Marketing materials",
      "Exclusive deals",
    ],
  },
  "thought-leadership": {
    title: "Thought Leadership",
    subtitle: "Shaping the Future of Tech",
    description: "Netwit thought leaders are shaping the future of technology through innovation, research, and industry expertise. Discover insights that drive the future of digital transformation.",
    stats: [
      { value: "50+", label: "Thought Leaders" },
      { value: "500+", label: "Publications" },
      { value: "100K+", label: "Reader Reach" },
      { value: "20+", label: "Industry Awards" },
    ],
    highlights: [
      "Industry experts",
      "Research papers",
      "Conference talks",
      "Media appearances",
    ],
  },
};

export const aboutList = Object.entries(aboutData).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
}));
