export const industriesData = {
  // Who We Serve
  startups: {
    title: "Startups",
    subtitle: "Scale Your Startup with AI-Powered DevOps",
    category: "Who We Serve",
    description: "Accelerate your startup's growth with our AI-powered DevOps solutions. From MVP to scale-up, we provide the infrastructure and automation you need to move fast and stay secure.",
    challenges: [
      "Limited resources and budget",
      "Need for rapid scaling",
      "Security concerns",
      "Quick deployment cycles",
    ],
    solutions: [
      "Cloud-native infrastructure",
      "Automated CI/CD pipelines",
      "Scalable architecture",
      "Cost-effective solutions",
    ],
    benefits: [
      "50% faster time-to-market",
      "Reduced infrastructure costs",
      "Enterprise-grade security",
      "24/7 support",
    ],
  },
  scaleups: {
    title: "Scaleups",
    subtitle: "Accelerate Growth with Enterprise DevOps",
    category: "Who We Serve",
    description: "Take your scaleup to the next level with our enterprise-grade DevOps solutions. We help you scale infrastructure, automate processes, and maintain quality as you grow.",
    challenges: [
      "Scaling infrastructure rapidly",
      "Maintaining code quality",
      "Complex deployment workflows",
      "Team coordination",
    ],
    solutions: [
      "Kubernetes orchestration",
      "Advanced CI/CD automation",
      "Microservices architecture",
      "DevSecOps implementation",
    ],
    benefits: [
      "Seamless scaling",
      "Improved team productivity",
      "Faster releases",
      "Better collaboration",
    ],
  },
  enterprises: {
    title: "Enterprises",
    subtitle: "Transform Your Enterprise with AI DevOps",
    category: "Who We Serve",
    description: "Modernize your enterprise IT with AI-driven DevOps solutions. We help large organizations accelerate digital transformation while maintaining compliance and security.",
    challenges: [
      "Legacy system modernization",
      "Compliance and security",
      "Complex workflows",
      "Large team coordination",
    ],
    solutions: [
      "Hybrid cloud solutions",
      "Zero-trust security",
      "Compliance automation",
      "Enterprise integration",
    ],
    benefits: [
      "Modernized infrastructure",
      "Regulatory compliance",
      "Improved efficiency",
      "Digital transformation",
    ],
  },
  saas: {
    title: "Product / SaaS Firm",
    subtitle: "Build and Scale Your SaaS Products",
    category: "Who We Serve",
    description: "Build, deploy, and scale your SaaS products with our specialized DevOps solutions. We understand the unique challenges of SaaS businesses and provide tailored solutions.",
    challenges: [
      "Multi-tenant architecture",
      "High availability requirements",
      "Continuous feature delivery",
      "Customer data security",
    ],
    solutions: [
      "SaaS-ready infrastructure",
      "Auto-scaling solutions",
      "Blue-green deployments",
      "Data encryption",
    ],
    benefits: [
      "99.99% uptime",
      "Frequent releases",
      "Secure multi-tenancy",
      "Cost optimization",
    ],
  },
  "it-staff": {
    title: "IT Staff Agency",
    subtitle: "Augment Your IT Team with DevOps Experts",
    category: "Who We Serve",
    description: "Bridge your talent gap with our IT staff augmentation services. Get access to certified DevOps engineers who integrate seamlessly with your team.",
    challenges: [
      "Talent shortage",
      "Skill gaps",
      "Quick project needs",
      "Cost management",
    ],
    solutions: [
      "Dedicated DevOps engineers",
      "Team augmentation",
      "Knowledge transfer",
      "Flexible engagement",
    ],
    benefits: [
      "Access to experts",
      "Faster project completion",
      "Cost-effective",
      "Knowledge transfer",
    ],
  },
  // Industries Column 1
  education: {
    title: "Education & Learning",
    subtitle: "DevOps for EdTech and Educational Institutions",
    category: "Industries",
    description: "Transform educational technology with our specialized DevOps solutions. Support online learning platforms, student information systems, and EdTech applications with reliable infrastructure.",
    challenges: [
      "High traffic during peak times",
      "Student data security",
      "Legacy system integration",
      "Accessibility requirements",
    ],
    solutions: [
      "Scalable cloud infrastructure",
      "GDPR compliant solutions",
      "API integrations",
      "CDN optimization",
    ],
    benefits: [
      "Reliable learning platforms",
      "Secure student data",
      "Better user experience",
      "Cost-effective scaling",
    ],
  },
  finance: {
    title: "Finance & Banking",
    subtitle: "Secure DevOps for Financial Services",
    category: "Industries",
    description: "Meet the demanding requirements of financial services with our secure, compliant DevOps solutions. We help banks, fintechs, and financial institutions modernize safely.",
    challenges: [
      "Strict regulatory compliance",
      "Security requirements",
      "Legacy mainframe systems",
      "Real-time transactions",
    ],
    solutions: [
      "PCI-DSS compliance",
      "Bank-grade security",
      "Mainframe modernization",
      "High-frequency trading infra",
    ],
    benefits: [
      "Regulatory compliance",
      "Enhanced security",
      "Faster innovation",
      "Reduced risk",
    ],
  },
  food: {
    title: "Food and Beverage",
    subtitle: "DevOps for Food Tech and Restaurants",
    category: "Industries",
    description: "Power your food tech and restaurant business with our specialized DevOps solutions. From delivery apps to supply chain management, we've got you covered.",
    challenges: [
      "Peak hour scalability",
      "Delivery app integration",
      "Inventory management",
      "Real-time analytics",
    ],
    solutions: [
      "Burstable infrastructure",
      "POS integrations",
      "Supply chain automation",
      "Real-time dashboards",
    ],
    benefits: [
      "Never miss an order",
      "Optimized operations",
      "Better insights",
      "Customer satisfaction",
    ],
  },
  healthcare: {
    title: "Healthcare",
    subtitle: "HIPAA-Compliant DevOps Solutions",
    category: "Industries",
    description: "Transform healthcare delivery with HIPAA-compliant DevOps solutions. We help healthcare providers, insurers, and health tech companies secure and scale their applications.",
    challenges: [
      "HIPAA compliance",
      "Patient data security",
      "Legacy medical systems",
      "Interoperability",
    ],
    solutions: [
      "HIPAA-compliant infrastructure",
      "Healthcare integrations",
      "FHIR API support",
      "Medical device security",
    ],
    benefits: [
      "Patient data protection",
      "Compliance assurance",
      "Better patient care",
      "Streamlined operations",
    ],
  },
  manufacturing: {
    title: "Manufacturing",
    subtitle: "Smart Manufacturing with DevOps",
    category: "Industries",
    description: "Enable Industry 4.0 with our manufacturing DevOps solutions. Connect machines, automate processes, and optimize production with modern infrastructure.",
    challenges: [
      "IoT integration",
      "Legacy PLC systems",
      "Real-time monitoring",
      "Supply chain visibility",
    ],
    solutions: [
      "IIoT infrastructure",
      "Edge computing",
      "Predictive maintenance",
      "Digital twin support",
    ],
    benefits: [
      "Smart factories",
      "Reduced downtime",
      "Optimized production",
      "Better analytics",
    ],
  },
  media: {
    title: "Media & Entertainment",
    subtitle: "DevOps for Streaming and Content",
    category: "Industries",
    description: "Deliver exceptional digital experiences with our media and entertainment DevOps solutions. From streaming platforms to gaming servers, we handle your content at scale.",
    challenges: [
      "Massive content delivery",
      "Global audience",
      "Peak traffic handling",
      "Content monetization",
    ],
    solutions: [
      "CDN integration",
      "Multi-CDN strategy",
      "Video transcoding",
      "Gaming server infrastructure",
    ],
    benefits: [
      "Global reach",
      "Zero buffering",
      "Scalable content",
      "Revenue optimization",
    ],
  },
  // Industries Column 2
  "real-estate": {
    title: "Real Estate",
    subtitle: "DevOps for Property Tech",
    category: "Industries",
    description: "Power your real estate technology with our specialized DevOps solutions. From property portals to property management systems, we ensure reliability and speed.",
    challenges: [
      "Property data management",
      "Map integrations",
      "Lead management",
      "MLS integrations",
    ],
    solutions: [
      "Scalable property databases",
      "Map API integrations",
      "CRM automation",
      "MLS connectivity",
    ],
    benefits: [
      "Fast property searches",
      "Better lead management",
      "Seamless integrations",
      "Improved conversions",
    ],
  },
  retail: {
    title: "Retail & Commerce",
    subtitle: "Omnichannel Retail DevOps",
    category: "Industries",
    description: "Build seamless retail experiences with our commerce DevOps solutions. Support e-commerce, POS, inventory, and customer loyalty programs at scale.",
    challenges: [
      "Black Friday scaling",
      "Inventory sync",
      "Payment processing",
      "Customer experience",
    ],
    solutions: [
      "Elastic e-commerce infra",
      "Real-time inventory",
      "Payment gateway integration",
      "Personalization engine",
    ],
    benefits: [
      "Never go down",
      "Unified commerce",
      "Better CX",
      "Higher conversions",
    ],
  },
  sports: {
    title: "Sports",
    subtitle: "DevOps for Sports Technology",
    category: "Industries",
    description: "Elevate fan experiences with our sports technology DevOps solutions. From streaming games to betting platforms, we handle peak sports traffic.",
    challenges: [
      "Live event traffic",
      "Betting latency",
      "Fan engagement",
      "Data analytics",
    ],
    solutions: [
      "Ultra-low latency infra",
      "Real-time data pipelines",
      "Fan engagement platforms",
      "Sports analytics",
    ],
    benefits: [
      "Zero lag experiences",
      "Engaged fans",
      "Real-time insights",
      "Revenue growth",
    ],
  },
  telecom: {
    title: "Telecommunication",
    subtitle: "DevOps for Telecom Providers",
    category: "Industries",
    description: "Modernize telecom infrastructure with our specialized DevOps solutions. Support billing, subscriber management, and 5G rollout with scalable systems.",
    challenges: [
      "5G infrastructure",
      "Billing modernization",
      "Network virtualization",
      "Subscriber management",
    ],
    solutions: [
      "5G-ready infrastructure",
      "Cloud billing systems",
      "NFV orchestration",
      "OSS/BSS integration",
    ],
    benefits: [
      "5G enablement",
      "Modern billing",
      "Network efficiency",
      "Subscriber satisfaction",
    ],
  },
  logistics: {
    title: "Transport & Logistics",
    subtitle: "Smart Logistics with DevOps",
    category: "Industries",
    description: "Optimize transport and logistics operations with our specialized DevOps solutions. From fleet management to warehouse automation, we power your logistics.",
    challenges: [
      "Fleet tracking",
      "Route optimization",
      "Warehouse management",
      "Last-mile delivery",
    ],
    solutions: [
      "GPS tracking infrastructure",
      "Route optimization AI",
      "WMS integration",
      "Delivery tracking",
    ],
    benefits: [
      "Real-time visibility",
      "Optimized routes",
      "Efficient warehouses",
      "Faster deliveries",
    ],
  },
  travel: {
    title: "Travel & Hospitality",
    subtitle: "DevOps for Travel Tech",
    category: "Industries",
    description: "Transform travel experiences with our hospitality DevOps solutions. Support booking engines, property management, and guest experiences at scale.",
    challenges: [
      "Seasonal traffic spikes",
      "Booking reliability",
      "Payment processing",
      "Guest experience",
    ],
    solutions: [
      "Burstable infrastructure",
      "Booking engine optimization",
      "Payment gateway integration",
      "Guest app infrastructure",
    ],
    benefits: [
      "Never miss bookings",
      "Seamless payments",
      "Happy guests",
      "Direct bookings",
    ],
  },
};

export const industriesList = Object.entries(industriesData).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
  category: data.category,
}));
