export const services = {
  "devops": {
    title: "DevOps Services",
    subtitle: "Accelerate Your Development Pipeline with Enterprise DevOps Solutions",
    description: "Transform your software delivery process with our comprehensive DevOps services. We help organizations achieve faster deployment cycles, improved collaboration, and reliable infrastructure management.",
    features: [
      { title: "CI/CD Pipeline", description: "Automated continuous integration and deployment pipelines" },
      { title: "Infrastructure as Code", description: "Scalable and reproducible infrastructure management" },
      { title: "Container Orchestration", description: "Kubernetes and Docker container management" },
      { title: "Cloud Migration", description: "Seamless migration to cloud platforms" },
      { title: "Monitoring & Logging", description: "Real-time monitoring and centralized logging" },
      { title: "Security Automation", description: "DevSecOps integration for secure deployments" },
    ],
    benefits: [
      "50% faster deployment cycles",
      "Reduced infrastructure costs",
      "Improved team collaboration",
      "Higher quality releases",
      "24/7 infrastructure support",
    ],
  },
  "sales-acceleration": {
    title: "Sales Acceleration",
    subtitle: "Supercharge Your Revenue Growth with AI-Powered Sales Solutions",
    description: "Accelerate your sales pipeline with our advanced sales acceleration services. We combine technology, strategy, and expertise to help you close deals faster.",
    features: [
      { title: "Lead Generation", description: "AI-powered prospect identification and qualification" },
      { title: "Sales Automation", description: "Automated follow-ups and task management" },
      { title: "CRM Integration", description: "Seamless Salesforce and HubSpot integration" },
      { title: "Sales Analytics", description: "Real-time pipeline insights and forecasting" },
      { title: "Email Automation", description: "Personalized outreach at scale" },
      { title: "Conversation Intelligence", description: "AI-powered call analysis and coaching" },
    ],
    benefits: [
      "40% increase in qualified leads",
      "30% shorter sales cycles",
      "Improved conversion rates",
      "Better sales forecasting",
      "Enhanced customer experience",
    ],
  },
  "qa-automation-testing": {
    title: "QA & Automation Testing",
    subtitle: "Deliver Flawless Software with Comprehensive Testing Solutions",
    description: "Ensure software quality with our end-to-end QA and automation testing services. We help you catch defects early and deliver reliable products to market.",
    features: [
      { title: "Test Automation", description: "Selenium, Cypress, and Playwright automation" },
      { title: "Performance Testing", description: "Load, stress, and endurance testing" },
      { title: "Security Testing", description: "Vulnerability assessment and penetration testing" },
      { title: "API Testing", description: "REST and GraphQL API validation" },
      { title: "Mobile Testing", description: "Cross-device and platform testing" },
      { title: "Continuous Testing", description: "Integration with CI/CD pipelines" },
    ],
    benefits: [
      "70% reduction in testing time",
      "99.9% defect detection rate",
      "Faster time-to-market",
      "Reduced manual testing costs",
      "Improved test coverage",
    ],
  },
  "accounting-services": {
    title: "Accounting Services",
    subtitle: "Streamline Your Financial Operations with Expert Accounting Solutions",
    description: "Transform your financial management with our comprehensive accounting services. From bookkeeping to financial analysis, we've got you covered.",
    features: [
      { title: "Bookkeeping", description: "Daily transaction recording and reconciliation" },
      { title: "Payroll Management", description: "Automated payroll processing and reporting" },
      { title: "Tax Preparation", description: "Strategic tax planning and compliance" },
      { title: "Financial Reporting", description: "Customized financial statements and analysis" },
      { title: "Accounts Payable", description: "Streamlined vendor payment processes" },
      { title: "Audit Support", description: "Preparation and coordination for audits" },
    ],
    benefits: [
      "Accurate financial records",
      "Tax savings and compliance",
      "Better cash flow management",
      "Reduced accounting costs",
      "Real-time financial insights",
    ],
  },
  "customer-support": {
    title: "Customer Support",
    subtitle: "Deliver Exceptional Customer Experiences with Modern Support Solutions",
    description: "Transform your customer support with AI-powered solutions that deliver fast, personalized, and consistent support across all channels.",
    features: [
      { title: "Live Chat", description: "Real-time customer assistance" },
      { title: "Email Support", description: "Automated ticket routing and responses" },
      { title: "Phone Support", description: "IVR and call center solutions" },
      { title: "Self-Service Portal", description: "Knowledge base and FAQ systems" },
      { title: "Social Media", description: "Multi-platform social customer care" },
      { title: "Analytics", description: "Customer satisfaction tracking and insights" },
    ],
    benefits: [
      "Faster response times",
      "Higher customer satisfaction",
      "Reduced support costs",
      "24/7 availability",
      "Consistent customer experience",
    ],
  },
  "marketing-services": {
    title: "Marketing Services",
    subtitle: "Grow Your Business with Data-Driven Marketing Solutions",
    description: "Amplify your brand presence and drive growth with our comprehensive marketing services. From digital marketing to content strategy, we help you reach your audience.",
    features: [
      { title: "Digital Marketing", description: "SEO, SEM, and online advertising" },
      { title: "Content Marketing", description: "Blog, whitepaper, and case study creation" },
      { title: "Social Media", description: "Platform management and community building" },
      { title: "Email Marketing", description: "Campaign automation and optimization" },
      { title: "Analytics", description: "Performance tracking and optimization" },
      { title: "Brand Strategy", description: "Positioning and brand development" },
    ],
    benefits: [
      "Increased brand awareness",
      "Higher lead generation",
      "Better ROI on ad spend",
      "Improved engagement rates",
      "Data-driven decisions",
    ],
  },
  "global-capability-center": {
    title: "Global Capability Center (GCC)",
    subtitle: "Build World-Class Operations with Our GCC Solutions",
    description: "Establish and optimize your Global Capability Center with our end-to-end solutions. We help you build efficient, scalable, and cost-effective operations.",
    features: [
      { title: "Setup & Launch", description: "End-to-end GCC establishment" },
      { title: "Process Optimization", description: "Streamlined operations and workflows" },
      { title: "Talent Acquisition", description: "Skilled team building and management" },
      { title: "Technology Implementation", description: "Tools and infrastructure setup" },
      { title: "Governance", description: "Performance monitoring and reporting" },
      { title: "Continuous Improvement", description: "Ongoing optimization and scaling" },
    ],
    benefits: [
      "40-60% cost savings",
      "Access to global talent",
      "24/7 operational coverage",
      "Scalable operations",
      "Focus on core business",
    ],
  },
};

export const solutions = {
  cybersecurity: {
    title: "End-to-End, AI-Powered Cybersecurity for SaaS Operation",
    subtitle: "360° protection for networks, endpoints, and cloud environments",
    label: "AI-Driven Cybersecurity Services & Solutions",
    buttonText: "Stay One Step Ahead with AI-Powered Cyber Defense",
    description: "Safeguard your organization with our comprehensive cybersecurity solutions. We provide end-to-end protection against evolving threats.",
    features: [
      { title: "Threat Detection", description: "AI-powered threat monitoring and detection" },
      { title: "Incident Response", description: "Rapid breach containment and recovery" },
      { title: "Vulnerability Management", description: "Proactive vulnerability assessment" },
      { title: "Security Audit", description: "Comprehensive security assessments" },
      { title: "Compliance", description: "Regulatory compliance management" },
      { title: "Training", description: "Security awareness programs" },
    ],
    benefits: [
      "Complete threat protection",
      "Regulatory compliance",
      "Reduced security incidents",
      "Business continuity",
      "Customer trust",
    ],
  },
  esg: {
    title: "Demystifying ESG",
    subtitle: "Understanding Environmental, Social, and Governance Framework",
    description: "Transform your business with our Environmental, Social, and Governance solutions. Achieve sustainability goals while improving business performance.",
    features: [
      { title: "ESG Assessment", description: "Comprehensive ESG maturity analysis" },
      { title: "Carbon Footprint", description: "Carbon emission tracking and reduction" },
      { title: "Sustainability Reporting", description: "GRI, SASB, and TCFD compliance" },
      { title: "Social Impact", description: "Community and workforce initiatives" },
      { title: "Governance", description: "Board diversity and ethics programs" },
      { title: "ESG Analytics", description: "Real-time ESG performance tracking" },
    ],
    benefits: [
      "Sustainable business practices",
      "Investor attraction",
      "Regulatory compliance",
      "Brand reputation",
      "Long-term value creation",
    ],
  },
  "ai-pods": {
    title: "AI Pods",
    subtitle: "Deploy Dedicated AI Teams for Your Business",
    description: "Accelerate your AI initiatives with our dedicated AI Pods. Get a team of experts focused on delivering AI solutions tailored to your business needs.",
    features: [
      { title: "Dedicated Team", description: "Full-time AI specialists" },
      { title: "Machine Learning", description: "Custom ML model development" },
      { title: "NLP Solutions", description: "Natural language processing" },
      { title: "Computer Vision", description: "Image and video analysis" },
      { title: "Predictive Analytics", description: "Forecasting and insights" },
      { title: "AI Strategy", description: "Roadmap and implementation planning" },
    ],
    benefits: [
      "Faster AI implementation",
      "Dedicated expertise",
      "Scalable AI capabilities",
      "Reduced time-to-value",
      "Continuous innovation",
    ],
  },
  "data-pods": {
    title: "Data Pods",
    subtitle: "Unlock Insights with Dedicated Data Teams",
    description: "Transform your data into actionable insights with our Data Pods. Get a dedicated team focused on data engineering, analytics, and visualization.",
    features: [
      { title: "Data Engineering", description: "Pipeline and architecture design" },
      { title: "Data Analytics", description: "Advanced data analysis" },
      { title: "Data Visualization", description: "Interactive dashboards" },
      { title: "Data Governance", description: "Quality and security management" },
      { title: "Business Intelligence", description: "BI strategy and implementation" },
      { title: "Data Strategy", description: "Roadmap and governance planning" },
    ],
    benefits: [
      "Data-driven decisions",
      "Improved data quality",
      "Faster insights",
      "Better business outcomes",
      "Scalable data infrastructure",
    ],
  },
  "azure-migration": {
    title: "Azure Migration",
    subtitle: "Seamless Cloud Migration to Microsoft Azure",
    description: "Transform your infrastructure with our Azure migration services. We ensure a smooth, secure, and efficient transition to the cloud.",
    features: [
      { title: "Assessment", description: "Workload analysis and planning" },
      { title: "Migration Strategy", description: "Phased migration approach" },
      { title: "Lift & Shift", description: "Quick cloud migration" },
      { title: "Re-architecting", description: "Cloud-native optimization" },
      { title: "Hybrid Cloud", description: "Azure hybrid solutions" },
      { title: "Cost Optimization", description: "Cloud spend management" },
    ],
    benefits: [
      "Reduced infrastructure costs",
      "Improved scalability",
      "Enhanced security",
      "Business continuity",
      "Faster innovation",
    ],
  },
  "managed-detection-response": {
    title: "Managed Detection Response",
    subtitle: "24/7 Security Monitoring and Rapid Response",
    description: "Protect your business round-the-clock with our Managed Detection and Response services. Advanced threat detection and rapid incident response.",
    features: [
      { title: "Continuous Monitoring", description: "24/7 security operations center" },
      { title: "Threat Detection", description: "AI-powered anomaly detection" },
      { title: "Incident Response", description: "Rapid threat containment" },
      { title: "Threat Hunting", description: "Proactive threat identification" },
      { title: "Log Management", description: "Centralized log analysis" },
      { title: "Reporting", description: "Detailed security insights" },
    ],
    benefits: [
      "Real-time threat protection",
      "Faster incident response",
      "Reduced security costs",
      "Compliance support",
      "Peace of mind",
    ],
  },
};

export const servicesList = Object.entries(services).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
}));

export const solutionsList = Object.entries(solutions).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
}));
export const qaSubServices = {
  "functional-testing": {
    title: "Functional Testing",
    subtitle: "Precision Validation of Every Application Feature",
    description: "Our functional testing services ensure that your software behaves exactly as intended. We use AI-driven test modeling to cover every user scenario, from core business logic to edge cases, ensuring 100% adherence to requirements.",
    features: [
      { title: "AI-Powered Test Modeling", description: "Automated test case generation based on application architecture." },
      { title: "Boundary Value Analysis", description: "Rigorous testing of input limits and data constraints." },
      { title: "End-to-End Workflow Validation", description: "Verifying complex user journeys across multiple integrated systems." },
      { title: "Exploratory Testing", description: "Human-centric testing to identify unexpected defects." },
    ],
    benefits: [
      "100% requirements compliance",
      "Early defect detection",
      "Enhanced user satisfaction",
      "Stable and predictable software behavior",
    ],
  },
  "performance-testing": {
    title: "Performance Testing",
    subtitle: "Optimize Velocity and Scalability for Peak Traffic",
    description: "We push your application to its limits to ensure it remains stable, responsive, and fast under any load. Our engineers simulate massive concurrent user traffic to identify bottlenecks before they affect your users.",
    features: [
      { title: "Load & Stress Testing", description: "Simulating high-volume traffic to determine breaking points." },
      { title: "Scalability Assessment", description: "Verifying how your infrastructure handles rapid growth." },
      { title: "Endurance Testing", description: "Ensuring long-term stability under continuous operational load." },
      { title: "Network Latency Analysis", description: "Optimizing response times across global regions." },
    ],
    benefits: [
      "No downtime during peak traffic",
      "Optimized infrastructure costs",
      "Ultra-fast page load times",
      "Proactive bottleneck identification",
    ],
  },
  "security-testing": {
    title: "Security Testing",
    subtitle: "Fortify Your SaaS Ecosystem Against Modern Threats",
    description: "Protecting user data is non-negotiable. We conduct rigorous security assessments, including vulnerability scanning and penetration testing, to safeguard your application from unauthorized access and data breaches.",
    features: [
      { title: "Penetration Testing", description: "Simulated cyber-attacks to identify exploitable vulnerabilities." },
      { title: "Static & Dynamic Analysis (SAST/DAST)", description: "Automated code and runtime security auditing." },
      { title: "Compliance Auditing", description: "Ensuring adherence to NIST, GDPR, and SOC2 standards." },
      { title: "Data Integrity Validation", description: "Verifying encryption and secure data handling protocols." },
    ],
    benefits: [
      "Zero-compromise data security",
      "Regulatory compliance assurance",
      "Enhanced customer trust",
      "Minimized risk of data breaches",
    ],
  },
  "regression-testing": {
    title: "Regression Testing",
    subtitle: "Ship Updates with Confidence and Stability",
    description: "Every new feature should enhance your product, not break it. Our automated regression suites ensure that your core functionalities remain intact after every deployment using self-healing AI scripts.",
    features: [
      { title: "Self-Healing Test Suites", description: "AI-driven scripts that automatically adapt to UI changes." },
      { title: "Change Impact Analysis", description: "Identifying precisely which areas need re-testing after an update." },
      { title: "Parallel Test Execution", description: "Running hundreds of tests simultaneously for rapid feedback." },
      { title: "Standardized Build Validation", description: "Strict checks before any code reaches production." },
    ],
    benefits: [
      "Faster deployment cycles",
      "No unexpected regressions",
      "Reduced manual testing effort",
      "High-confidence release cycles",
    ],
  },
  "cicd-testing": {
    title: "CI/CD Pipeline Testing",
    subtitle: "Automated Validation for Modern Engineering Velocity",
    description: "We integrate automated testing into your DevOps pipeline, ensuring that every commit is validated before it moves forward. This 'Shift Left' approach identifies bugs earlier, reducing costs and accelerating delivery.",
    features: [
      { title: "Pipeline Integration", description: "Seamless embedding of tests into Jenkins, GitHub Actions, or GitLab." },
      { title: "Gated Deployment Logic", description: "Automatically halting builds that don't meet quality standards." },
      { title: "Real-time Feedback Loops", description: "Immediate reports for developers after every code push." },
      { title: "Infrastructure-as-Tests", description: "Validating infrastructure configurations alongside application code." },
    ],
    benefits: [
      "Accelerated time-to-market",
      "Reduced manual intervention",
      "Lower cost per defect",
      "Continuous quality assurance",
    ],
  },
  "ui-ux-automation": {
    title: "UI/UX Automation",
    subtitle: "Pixel-Perfect Visual and Experiential Excellence",
    description: "Guarantee a consistent and beautiful experience across all devices and browsers. We use visual regression tools and pixel-perfect comparison to ensure your brand's aesthetic remains flawless in every deployment.",
    features: [
      { title: "Visual Regression Testing", description: "Identifying unintended UI changes at the pixel level." },
      { title: "Cross-Browser/Device Matrix", description: "Testing across Chrome, Safari, iOS, and Android ecosystems." },
      { title: "Accessibility (a11y) Audits", description: "Ensuring compliance with WCAG standards for all users." },
      { title: "User Journey Automation", description: "Simulating real human interactions to verify UX flow." },
    ],
    benefits: [
      "Consistent brand experience",
      "Flawless cross-platform display",
      "Improved mobile conversion",
      "Full accessibility compliance",
    ],
  },
};
