export const resourcesData = {
  "case-studies": {
    title: "Case Studies",
    subtitle: "Success Stories That Inspire",
    description: "Explore our success stories and learn how we've helped businesses transform their operations, accelerate growth, and achieve remarkable results through innovative DevOps solutions.",
    category: "Case Studies",
    items: [
      { title: "How We Helped a Startup Scale to 1M Users", description: "Cloud infrastructure case study", tag: "Featured" },
      { title: "Enterprise DevOps Transformation", description: "A Fortune 500 company's journey", tag: "Enterprise" },
      { title: "Mobile App Success Story", description: "Building a scalable fintech platform", tag: "Fintech" },
      { title: "Healthcare Compliance Made Easy", description: "HIPAA-compliant cloud solutions", tag: "Healthcare" },
      { title: "Retail Transformation with AI", description: "E-commerce platform modernization", tag: "Retail" },
      { title: "Manufacturing IoT Implementation", description: "Smart factory solutions", tag: "Manufacturing" },
    ],
  },
  "client-experiences": {
    title: "Client Experiences",
    subtitle: "What Our Clients Say",
    description: "Read testimonials and success stories from our valued clients. Discover how we've helped organizations across industries achieve their business goals.",
    category: "Testimonials",
    items: [
      { title: "Exceptional DevOps Support", description: "Client from SaaS industry", tag: "5 Stars" },
      { title: "Transformed Our Infrastructure", description: "Client from healthcare", tag: "5 Stars" },
      { title: "Best Team We've Worked With", description: "Client from fintech", tag: "Recommended" },
      { title: "Outstanding Results", description: "Client from retail", tag: "5 Stars" },
      { title: "Professional & Reliable", description: "Client from logistics", tag: "Recommended" },
      { title: "Highly Recommend", description: "Client from education", tag: "5 Stars" },
    ],
  },
  blog: {
    title: "Blog",
    subtitle: "Latest Insights & Updates",
    description: "Stay updated with the latest trends, insights, and expert opinions on DevOps, cloud computing, AI, cybersecurity, and digital transformation.",
    category: "Blog",
    items: [
      { title: "The Future of DevOps in 2025", description: "Trends and predictions", tag: "Trending" },
      { title: "AI in Cloud Computing", description: "How AI is transforming cloud", tag: "AI" },
      { title: "Kubernetes Best Practices", description: "Expert guide", tag: "Technical" },
      { title: "Cybersecurity Trends", description: "Protect your business", tag: "Security" },
      { title: "DevOps vs Platform Engineering", description: "What's the difference?", tag: "Guide" },
      { title: "Cloud Cost Optimization", description: "Save on cloud spending", tag: "Tutorial" },
    ],
  },
  webinars: {
    title: "Webinars",
    subtitle: "Live & Recorded Sessions",
    description: "Join our expert-led webinars on DevOps, cloud computing, AI, cybersecurity, and more. Learn from industry experts and get your questions answered live.",
    category: "Webinars",
    items: [
      { title: "DevOps Best Practices Workshop", description: "Live session with Q&A", tag: "Live" },
      { title: "Cloud Migration Strategies", description: "Step-by-step guide", tag: "Recorded" },
      { title: "AI in Enterprise", description: "Expert panel discussion", tag: "Recorded" },
      { title: "Security in the Cloud", description: "Best practices webinar", tag: "Live" },
      { title: "Kubernetes Deep Dive", description: "Technical workshop", tag: "Recorded" },
      { title: "DevOps Transformation", description: "Success stories", tag: "Live" },
    ],
  },
  "press-release": {
    title: "Press Release",
    subtitle: "Company News & Announcements",
    description: "Read the latest press releases and company announcements. Stay informed about our new services, partnerships, awards, and organizational updates.",
    category: "Press",
    items: [
      { title: "Netwit Launches AI-Powered DevOps", description: "New AI services announcement", tag: "News" },
      { title: "Partnership with AWS", description: "Cloud partnership", tag: "Partnership" },
      { title: "Award for Innovation", description: "Industry recognition", tag: "Award" },
      { title: "Expansion to Europe", description: "Global expansion", tag: "News" },
      { title: "New CTO Appointed", description: "Leadership update", tag: "News" },
      { title: "Sustainability Initiative", description: "Green computing", tag: "CSR" },
    ],
  },
  "expert-qa": {
    title: "Expert Q & A",
    subtitle: "Ask Our Experts",
    description: "Get your burning questions answered by our team of DevOps experts. Browse through previous Q&A sessions or submit your own question.",
    category: "Q&A",
    items: [
      { title: "DevOps Implementation FAQ", description: "Common questions answered", tag: "Popular" },
      { title: "Cloud Security Q&A", description: "Security expert session", tag: "Security" },
      { title: "AI Integration FAQ", description: "AI experts answer", tag: "AI" },
      { title: "Kubernetes Troubleshooting", description: "Technical Q&A", tag: "Technical" },
      { title: "Cost Optimization Tips", description: "Finance team Q&A", tag: "Popular" },
      { title: "Compliance Questions", description: "Regulatory experts", tag: "Compliance" },
    ],
  },
  podcasts: {
    title: "Podcasts",
    subtitle: "Listen & Learn",
    description: "Tune into our podcasts featuring industry experts, thought leaders, and our team. Learn about the latest trends, tips, and insights in the world of technology.",
    category: "Podcasts",
    items: [
      { title: "DevOps Unplugged Ep. 1", description: "The future of DevOps", tag: "Audio" },
      { title: "Cloud Stories Ep. 2", description: "Customer success stories", tag: "Audio" },
      { title: "Tech Talks Ep. 3", description: "AI & machine learning", tag: "Audio" },
      { title: "Startup Stories Ep. 4", description: "Scaling tips", tag: "Audio" },
      { title: "Security First Ep. 5", description: "Cybersecurity insights", tag: "Audio" },
      { title: "Innovation Weekly Ep. 6", description: "Latest tech trends", tag: "Audio" },
    ],
  },
  whitepapers: {
    title: "Whitepapers",
    subtitle: "In-Depth Technical Guides",
    description: "Download our comprehensive whitepapers on advanced technical topics. Get detailed insights, best practices, and research-backed strategies.",
    category: "Whitepapers",
    items: [
      { title: "Enterprise DevOps Guide", description: "Complete implementation guide", tag: "Download" },
      { title: "Cloud Architecture Patterns", description: "Scalable designs", tag: "Download" },
      { title: "AI Implementation Strategy", description: "Executive guide", tag: "Download" },
      { title: "Security Compliance Handbook", description: "Regulatory guide", tag: "Download" },
      { title: "Cost Optimization Playbook", description: "Save strategies", tag: "Download" },
      { title: "DevOps Maturity Model", description: "Assessment framework", tag: "Download" },
    ],
  },
  ebooks: {
    title: "eBooks",
    subtitle: "Comprehensive Guides",
    description: "Download our in-depth eBooks covering various topics from DevOps fundamentals to advanced cloud strategies. Perfect for learning at your own pace.",
    category: "eBooks",
    items: [
      { title: "DevOps for Beginners", description: "Start your journey", tag: "Free" },
      { title: "Cloud Computing Guide", description: "Complete overview", tag: "Free" },
      { title: "AI in Business", description: "Executive guide", tag: "Premium" },
      { title: "Security Best Practices", description: "Protect your business", tag: "Free" },
      { title: "DevOps Tools Comparison", description: "Technical guide", tag: "Premium" },
      { title: "Scaling Your Startup", description: "Growth strategies", tag: "Free" },
    ],
  },
  brochure: {
    title: "Brochure",
    subtitle: "Company Overview",
    description: "Download our company brochure to learn about our services, capabilities, and success stories. Get a comprehensive overview of what we offer.",
    category: "Brochure",
    items: [
      { title: "Company Profile", description: "Overview & capabilities", tag: "Download" },
      { title: "Services Overview", description: "Complete service list", tag: "Download" },
      { title: "Industry Solutions", description: "Vertical expertise", tag: "Download" },
      { title: "Case Studies Summary", description: "Success highlights", tag: "Download" },
      { title: "Partnership Program", description: "For partners", tag: "Download" },
      { title: "Career Opportunities", description: "Join our team", tag: "Download" },
    ],
  },
  infographics: {
    title: "Infographics",
    subtitle: "Visual Learning",
    description: "Explore our visually engaging infographics that simplify complex topics. Perfect for quick learning and sharing with your team.",
    category: "Infographics",
    items: [
      { title: "DevOps Lifecycle", description: "Visual guide", tag: "View" },
      { title: "Cloud Comparison", description: "AWS vs Azure vs GCP", tag: "View" },
      { title: "Security Checklist", description: "Quick reference", tag: "View" },
      { title: "AI Benefits", description: "Infographic", tag: "View" },
      { title: "Cost Breakdown", description: "Cloud costs", tag: "View" },
      { title: "Team Structure", description: "DevOps roles", tag: "View" },
    ],
  },
  "tech-tales": {
    title: "Tech Tales",
    subtitle: "Stories from the Field",
    description: "Read real-world technical stories from our projects. Learn about challenges, solutions, and lessons learned from our engineering team.",
    category: "Stories",
    items: [
      { title: "Scaling a Million Users", description: "Infrastructure story", tag: "Popular" },
      { title: "Zero Downtime Migration", description: "Cloud migration tale", tag: "Technical" },
      { title: "Building a Chatbot", description: "AI project story", tag: "AI" },
      { title: "24/7 Support Chronicles", description: "Operations story", tag: "Popular" },
      { title: "Debugging Journey", description: "Troubleshooting tale", tag: "Technical" },
      { title: "Startup to Enterprise", description: "Growth story", tag: "Story" },
    ],
  },
  "saas-masterclasses": {
    title: "SaaS Masterclasses",
    subtitle: "Expert-Led Training",
    description: "Enroll in our exclusive masterclasses taught by industry experts. Learn advanced concepts and practical skills to accelerate your career.",
    category: "Masterclasses",
    items: [
      { title: "Advanced Kubernetes", description: "Expert workshop", tag: "Premium" },
      { title: "AWS Solutions Architect", description: "Certification prep", tag: "Premium" },
      { title: "DevOps Leadership", description: "Management skills", tag: "Premium" },
      { title: "Cloud Security", description: "Security expert", tag: "Premium" },
      { title: "AI/ML Implementation", description: "Technical deep dive", tag: "Premium" },
      { title: "Platform Engineering", description: "Modern DevOps", tag: "Premium" },
    ],
  },
  faq: {
    title: "FAQ",
    subtitle: "Frequently Asked Questions",
    description: "Find answers to commonly asked questions about our services, processes, pricing, and more. Get quick answers to your queries.",
    category: "FAQ",
    items: [
      { title: "What is DevOps?", description: "Basic explanation", tag: "Popular" },
      { title: "How long does implementation take?", description: "Timeline FAQ", tag: "Popular" },
      { title: "What are your pricing plans?", description: "Cost information", tag: "Popular" },
      { title: "Do you offer support?", description: "Support details", tag: "Service" },
      { title: "What industries do you serve?", description: "Industries", tag: "General" },
      { title: "How do I get started?", description: "Onboarding", tag: "Popular" },
    ],
  },
  "all-resources": {
    title: "All Resources",
    subtitle: "Everything in One Place",
    description: "Browse our complete collection of resources including case studies, blogs, webinars, podcasts, whitepapers, and more.",
    category: "All",
    items: [
      { title: "Latest Case Studies", description: "Success stories", tag: "Case Studies" },
      { title: "Recent Blog Posts", description: "Fresh insights", tag: "Blog" },
      { title: "Webinar Recordings", description: "Watch sessions", tag: "Webinars" },
      { title: "Technical Whitepapers", description: "In-depth guides", tag: "Whitepapers" },
      { title: "Podcast Episodes", description: "Listen & learn", tag: "Podcasts" },
      { title: "eBook Collection", description: "Download guides", tag: "eBooks" },
    ],
  },
};

export const resourcesList = Object.entries(resourcesData).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
  category: data.category,
}));
