export const hireData = {
  "generative-ai": {
    title: "Generative AI",
    subtitle: "Hire Expert Generative AI Developers",
    description: "Transform your business with our expert Generative AI development services. Hire dedicated AI engineers who specialize in LLMs, GPT models, and custom AI solutions.",
    features: [
      { title: "Custom LLM Development", description: "Build tailored language models for your specific needs" },
      { title: "GPT Integration", description: "Seamless integration with OpenAI GPT models" },
      { title: "AI Content Generation", description: "Automated content creation for marketing and products" },
      { title: "Conversational AI", description: "Intelligent chatbots and virtual assistants" },
    ],
    benefits: [
      "Access to top 1% AI talent",
      "Flexible engagement models",
      "Cost-effective development",
      "Cutting-edge AI solutions",
    ],
  },
  devops: {
    title: "DevOps",
    subtitle: "Hire Expert DevOps Engineers",
    description: "Accelerate your software delivery with our expert DevOps engineers. Hire dedicated professionals who specialize in CI/CD, cloud infrastructure, and automation.",
    features: [
      { title: "CI/CD Pipeline", description: "Automated continuous integration and deployment" },
      { title: "Cloud Infrastructure", description: "AWS, Azure, and GCP expertise" },
      { title: "Container Orchestration", description: "Kubernetes and Docker mastery" },
      { title: "Infrastructure as Code", description: "Terraform and Ansible automation" },
    ],
    benefits: [
      "50% faster deployments",
      "Reduced downtime",
      "24/7 infrastructure support",
      "Enterprise-grade security",
    ],
  },
  "lead-generation": {
    title: "Lead Generation",
    subtitle: "Hire Lead Generation Specialists",
    description: "Drive revenue growth with our expert lead generation specialists. Hire professionals who use AI-powered tools and proven strategies to qualify and convert leads.",
    features: [
      { title: "AI-Powered Prospecting", description: "Smart lead identification and qualification" },
      { title: "Multi-channel Outreach", description: "Email, LinkedIn, and cold calling" },
      { title: "CRM Integration", description: "Seamless Salesforce and HubSpot integration" },
      { title: "Lead Scoring", description: "Data-driven lead prioritization" },
    ],
    benefits: [
      "3x more qualified leads",
      "Higher conversion rates",
      "Reduced customer acquisition cost",
      "Scalable lead pipeline",
    ],
  },
  "product-development": {
    title: "Product Development",
    subtitle: "Hire Product Development Teams",
    description: "Build world-class products with our dedicated product development teams. Hire experienced developers, designers, and product managers who deliver results.",
    features: [
      { title: "Agile Development", description: "Iterative and flexible development process" },
      { title: "Product Design", description: "UI/UX design and prototyping" },
      { title: "Full-Stack Development", description: "End-to-end product engineering" },
      { title: "MVP Development", description: "Fast-track minimum viable products" },
    ],
    benefits: [
      "Faster time-to-market",
      "Experienced product teams",
      "Reduced development costs",
      "Quality assurance",
    ],
  },
  "web-application-development": {
    title: "Web Application Development",
    subtitle: "Hire Web App Developers",
    description: "Create powerful web applications with our expert developers. Hire professionals who specialize in modern frameworks and scalable architectures.",
    features: [
      { title: "Modern Frameworks", description: "React, Vue, Angular expertise" },
      { title: "Progressive Web Apps", description: "PWA development for better UX" },
      { title: "API Development", description: "RESTful and GraphQL APIs" },
      { title: "Cloud-Native Apps", description: "Scalable cloud architecture" },
    ],
    benefits: [
      "High-performance apps",
      "SEO-friendly solutions",
      "Cross-browser compatibility",
      "Responsive design",
    ],
  },
  "mobile-app-development": {
    title: "Mobile App Development",
    subtitle: "Hire Mobile App Developers",
    description: "Build stunning mobile applications with our expert developers. Hire professionals who create native and cross-platform apps for iOS and Android.",
    features: [
      { title: "Native Development", description: "iOS Swift and Android Kotlin" },
      { title: "Cross-Platform", description: "React Native and Flutter apps" },
      { title: "App Store Optimization", description: "ASO and deployment services" },
      { title: "Maintenance", description: "Ongoing support and updates" },
    ],
    benefits: [
      "Native performance",
      "Faster development",
      "App store success",
      "Post-launch support",
    ],
  },
  "erp-crm-implementation": {
    title: "ERP & CRM Implementation",
    subtitle: "Hire ERP & CRM Specialists",
    description: "Streamline your business operations with our ERP and CRM implementation experts. Hire specialists who ensure seamless integration and adoption.",
    features: [
      { title: "Salesforce", description: "CRM implementation and customization" },
      { title: "SAP", description: "Enterprise resource planning" },
      { title: "Microsoft Dynamics", description: "Business solution implementation" },
      { title: "Custom Integration", description: "Connect all your business systems" },
    ],
    benefits: [
      "Improved efficiency",
      "Better customer relationships",
      "Data-driven decisions",
      "ROI within months",
    ],
  },
  "ecommerce-development": {
    title: "eCommerce Development",
    subtitle: "Hire eCommerce Developers",
    description: "Build high-converting online stores with our expert eCommerce developers. Hire professionals who create scalable, secure, and user-friendly shopping experiences.",
    features: [
      { title: "Shopify Development", description: "Custom Shopify stores and apps" },
      { title: "WooCommerce", description: "WordPress eCommerce solutions" },
      { title: "Custom Platforms", description: "Tailored eCommerce development" },
      { title: "Payment Integration", description: "Secure payment gateway setup" },
    ],
    benefits: [
      "Higher conversions",
      "Mobile-optimized stores",
      "Secure transactions",
      "SEO-friendly platforms",
    ],
  },
  "qa-software-testing": {
    title: "QA / Software Testing",
    subtitle: "Hire QA Engineers",
    description: "Ensure flawless software quality with our expert QA engineers. Hire dedicated testers who use manual and automated testing to deliver bug-free products.",
    features: [
      { title: "Test Automation", description: "Selenium, Cypress, Playwright" },
      { title: "Performance Testing", description: "Load and stress testing" },
      { title: "Security Testing", description: "Vulnerability assessment" },
      { title: "Manual Testing", description: "Comprehensive test cases" },
    ],
    benefits: [
      "99.9% bug-free releases",
      "Reduced rework costs",
      "Faster time-to-market",
      "Improved user satisfaction",
    ],
  },
  salesforce: {
    title: "Salesforce",
    subtitle: "Hire Salesforce Developers",
    description: "Maximize your CRM investment with our expert Salesforce developers. Hire certified professionals who customize and optimize your Salesforce ecosystem.",
    features: [
      { title: "Sales Cloud", description: "Sales automation and pipeline management" },
      { title: "Service Cloud", description: "Customer service and support" },
      { title: "Marketing Cloud", description: "Marketing automation" },
      { title: "Custom Development", description: "Apex, Visualforce, Lightning" },
    ],
    benefits: [
      "Maximized ROI",
      "Better adoption rates",
      "Custom solutions",
      "Ongoing support",
    ],
  },
};

export const technologyData = {
  // Frontend
  angularjs: {
    title: "AngularJS Development",
    subtitle: "Build Enterprise Web Applications",
    description: "Create robust enterprise web applications with our expert AngularJS development services. Our developers build scalable, maintainable, and high-performance applications.",
    features: [
      { title: "Enterprise Apps", description: "Scalable business applications" },
      { title: "SPA Development", description: "Single page application expertise" },
      { title: "Component Architecture", description: "Reusable UI components" },
      { title: "TypeScript Development", description: "Type-safe code practices" },
    ],
    benefits: [
      "Maintainable codebase",
      "High performance",
      "Two-way data binding",
      "Strong community support",
    ],
  },
  reactjs: {
    title: "ReactJS Development",
    subtitle: "Build Modern User Interfaces",
    description: "Create stunning user interfaces with our expert ReactJS developers. Build fast, scalable, and interactive web applications with the most popular frontend framework.",
    features: [
      { title: "Custom Components", description: "Reusable React components" },
      { title: "State Management", description: "Redux and Context API expertise" },
      { title: "Next.js Development", description: "Server-side rendering" },
      { title: "Performance Optimization", description: "Code splitting and lazy loading" },
    ],
    benefits: [
      "Lightning-fast performance",
      "SEO-friendly",
      "Large ecosystem",
      "Easy to learn",
    ],
  },
  vuejs: {
    title: "Vue.js Development",
    subtitle: "Progressive JavaScript Framework",
    description: "Build progressive web applications with our Vue.js experts. Leverage the progressive framework that combines the best of Angular and React.",
    features: [
      { title: "Vue 3 Development", description: "Latest Vue.js version" },
      { title: "Nuxt.js Development", description: "Universal Vue.js apps" },
      { title: "Vuex State Management", description: "Centralized state management" },
      { title: "Component Libraries", description: "Vuetify and Element UI" },
    ],
    benefits: [
      "Gentle learning curve",
      "Flexible architecture",
      "Great documentation",
      "Reactive data binding",
    ],
  },
  nodejs: {
    title: "Node.js Development",
    subtitle: "Build Scalable Server-Side Apps",
    description: "Create high-performance server-side applications with our Node.js experts. Build scalable backends and APIs with the JavaScript runtime.",
    features: [
      { title: "RESTful APIs", description: "Scalable API development" },
      { title: "Express.js", description: "Fast web framework" },
      { title: "Real-time Apps", description: "WebSocket expertise" },
      { title: "Microservices", description: "Containerized architectures" },
    ],
    benefits: [
      "JavaScript everywhere",
      "High performance",
      "NPM ecosystem",
      "Non-blocking I/O",
    ],
  },
  // Mobile
  "react-native": {
    title: "React Native Development",
    subtitle: "Cross-Platform Mobile Apps",
    description: "Build cross-platform mobile apps with our React Native experts. Create native-quality iOS and Android apps with a single codebase.",
    features: [
      { title: "iOS & Android", description: "Both platforms from one code" },
      { title: "Native Modules", description: "Custom native integrations" },
      { title: "Redux Integration", description: "State management" },
      { title: "App Store Deployment", description: "Submission assistance" },
    ],
    benefits: [
      "Faster development",
      "Native performance",
      "Cost-effective",
      "Hot reloading",
    ],
  },
  flutter: {
    title: "Flutter Development",
    subtitle: "Beautiful Native Apps",
    description: "Create beautiful, natively compiled mobile applications with our Flutter experts. Build stunning iOS and Android apps from a single codebase.",
    features: [
      { title: "Dart Programming", description: "Optimized Flutter code" },
      { title: "Custom Widgets", description: "Beautiful UI components" },
      { title: "Firebase Integration", description: "Backend services" },
      { title: "Widgets Testing", description: "Comprehensive testing" },
    ],
    benefits: [
      "Beautiful UIs",
      "Single codebase",
      "Fast development",
      "Hot reload",
    ],
  },
  "ios-swift": {
    title: "iOS Swift Development",
    subtitle: "Native iOS Applications",
    description: "Build premium native iOS applications with our Swift experts. Create high-performance apps that leverage the full power of Apple's platforms.",
    features: [
      { title: "Swift Programming", description: "Modern Swift code" },
      { title: "SwiftUI", description: "Declarative UI framework" },
      { title: "Core Data", description: "Local data persistence" },
      { title: "App Store", description: "Deployment support" },
    ],
    benefits: [
      "Native performance",
      "Best user experience",
      "Security",
      "Apple ecosystem",
    ],
  },
  android: {
    title: "Android Development",
    subtitle: "Native Android Applications",
    description: "Create powerful native Android applications with our expert developers. Build apps that leverage the full potential of the Android platform.",
    features: [
      { title: "Kotlin Development", description: "Modern Android code" },
      { title: "Jetpack Compose", description: "Declarative UI" },
      { title: "Material Design", description: "Beautiful interfaces" },
      { title: "Play Store", description: "Deployment assistance" },
    ],
    benefits: [
      "Native performance",
      "Customization",
      "Google services",
      "Large audience",
    ],
  },
  ios: {
    title: "iOS Development",
    subtitle: "Premium iOS Applications",
    description: "Build exceptional iOS applications with our experienced developers. Create apps that stand out on the App Store with premium design and functionality.",
    features: [
      { title: "Objective-C", description: "Legacy iOS support" },
      { title: "Swift", description: "Modern iOS development" },
      { title: "UIKit", description: "Classic iOS framework" },
      { title: "Testing", description: "XCTest expertise" },
    ],
    benefits: [
      "Premium quality",
      "Apple ecosystem",
      "High retention",
      "Monetization",
    ],
  },
  // Backend
  php: {
    title: "PHP Development",
    subtitle: "Server-Side Scripting",
    description: "Build powerful server-side applications with our PHP experts. Create dynamic websites and web applications with the most popular server-side language.",
    features: [
      { title: "Laravel", description: "Modern PHP framework" },
      { title: "WordPress", description: "CMS development" },
      { title: "Symfony", description: "Enterprise PHP" },
      { title: "API Development", description: "RESTful services" },
    ],
    benefits: [
      "Wide ecosystem",
      "Easy deployment",
      "Cost-effective",
      "Large community",
    ],
  },
  "ruby-on-rails": {
    title: "Ruby on Rails Development",
    subtitle: "Rapid Application Development",
    description: "Build web applications rapidly with our Ruby on Rails experts. Leverage the convention-over-configuration framework for fast development.",
    features: [
      { title: "MVC Architecture", description: "Clean code structure" },
      { title: "Active Record", description: "Database ORM" },
      { title: "RESTful APIs", description: "API development" },
      { title: "Testing", description: "RSpec expertise" },
    ],
    benefits: [
      "Fast development",
      "Convention over config",
      "Secure by default",
      "Great for startups",
    ],
  },
  java: {
    title: "Java Development",
    subtitle: "Enterprise-Grade Solutions",
    description: "Build robust enterprise applications with our Java experts. Create scalable, secure, and maintainable systems with the world's most used programming language.",
    features: [
      { title: "Spring Framework", description: "Enterprise Java" },
      { title: "Microservices", description: "Cloud-native architecture" },
      { title: "REST APIs", description: "Web services" },
      { title: "Testing", description: "JUnit and Mockito" },
    ],
    benefits: [
      "Enterprise-grade",
      "Scalability",
      "Security",
      "Cross-platform",
    ],
  },
  python: {
    title: "Python Development",
    subtitle: "Versatile Programming",
    description: "Build versatile applications with our Python experts. From web development to AI/ML, our developers handle it all with Python's powerful ecosystem.",
    features: [
      { title: "Django", description: "Full-stack web framework" },
      { title: "Flask", description: "Lightweight web framework" },
      { title: "FastAPI", description: "Modern API framework" },
      { title: "AI/ML", description: "Machine learning integration" },
    ],
    benefits: [
      "Versatile",
      "Easy to learn",
      "AI/ML capabilities",
      "Great libraries",
    ],
  },
  dotnet: {
    title: ".NET Development",
    subtitle: "Microsoft Enterprise Solutions",
    description: "Build enterprise solutions with our .NET experts. Create scalable, secure, and Windows-integrated applications using Microsoft's robust framework.",
    features: [
      { title: "ASP.NET Core", description: "Cross-platform web framework" },
      { title: "Entity Framework", description: "Database ORM" },
      { title: "Xamarin", description: "Cross-platform mobile" },
      { title: "Azure", description: "Cloud integration" },
    ],
    benefits: [
      "Enterprise-ready",
      "Microsoft ecosystem",
      "Strong typing",
      "Security",
    ],
  },
  golang: {
    title: "Golang Development",
    subtitle: "High-Performance Backend",
    description: "Build high-performance backend systems with our Go experts. Create scalable microservices and APIs with the language designed for concurrency.",
    features: [
      { title: "Microservices", description: "Lightweight services" },
      { title: "Concurrency", description: "Goroutines and channels" },
      { title: "REST/gRPC", description: "API development" },
      { title: "Docker/K8s", description: "Containerization" },
    ],
    benefits: [
      "High performance",
      "Fast compilation",
      "Simplicity",
      "Scalability",
    ],
  },
  magento: {
    title: "Magento Development",
    subtitle: "Enterprise eCommerce",
    description: "Build powerful eCommerce platforms with our Magento experts. Create scalable online stores with the world's leading eCommerce framework.",
    features: [
      { title: "Magento 2", description: "Latest Magento version" },
      { title: "Custom Themes", description: "Beautiful storefronts" },
      { title: "Extensions", description: "Custom functionality" },
      { title: "Performance", description: "Optimization services" },
    ],
    benefits: [
      "Enterprise eCommerce",
      "Scalable",
      "SEO-friendly",
      "Rich features",
    ],
  },
  // Others
  "mean-stack": {
    title: "MEAN Stack Development",
    subtitle: "Full-Stack JavaScript",
    description: "Build full-stack JavaScript applications with our MEAN Stack experts. Create modern web apps using MongoDB, Express, Angular, and Node.js.",
    features: [
      { title: "MongoDB", description: "NoSQL database" },
      { title: "Express.js", description: "Web framework" },
      { title: "Angular", description: "Frontend framework" },
      { title: "Node.js", description: "Server runtime" },
    ],
    benefits: [
      "JavaScript everywhere",
      "JSON everywhere",
      "Flexible",
      "Fast development",
    ],
  },
  "mern-stack": {
    title: "MERN Stack Development",
    subtitle: "Modern Full-Stack JS",
    description: "Build modern web applications with our MERN Stack experts. Create powerful apps using MongoDB, Express, React, and Node.js.",
    features: [
      { title: "React", description: "Modern frontend" },
      { title: "Node.js", description: "Server-side JS" },
      { title: "MongoDB", description: "Flexible database" },
      { title: "Redux", description: "State management" },
    ],
    benefits: [
      "Modern architecture",
      "High performance",
      "Large ecosystem",
      "Job market demand",
    ],
  },
  "devops-azure": {
    title: "DevOps on Azure",
    subtitle: "Microsoft Cloud DevOps",
    description: "Implement DevOps practices on Microsoft Azure with our experts. Leverage Azure's powerful cloud services for automated deployments.",
    features: [
      { title: "Azure DevOps", description: "CI/CD pipelines" },
      { title: "Azure Kubernetes", description: "Container orchestration" },
      { title: "ARM Templates", description: "Infrastructure as Code" },
      { title: "Azure Functions", description: "Serverless computing" },
    ],
    benefits: [
      "Microsoft ecosystem",
      "Scalable cloud",
      "Enterprise security",
      "Hybrid capabilities",
    ],
  },
  "devops-aws": {
    title: "DevOps on AWS",
    subtitle: "Amazon Cloud DevOps",
    description: "Implement DevOps practices on AWS with our certified experts. Build scalable, secure applications using Amazon's cloud services.",
    features: [
      { title: "CodePipeline", description: "CI/CD automation" },
      { title: "ECS/EKS", description: "Container services" },
      { title: "CloudFormation", description: "IaC templates" },
      { title: "Lambda", description: "Serverless" },
    ],
    benefits: [
      "Market leader",
      "Scalability",
      "Security",
      "Global infrastructure",
    ],
  },
  "dynamics-crm": {
    title: "Microsoft Dynamics CRM",
    subtitle: "Enterprise CRM Solutions",
    description: "Implement and customize Microsoft Dynamics CRM with our experts. Optimize your customer relationships with powerful CRM solutions.",
    features: [
      { title: "Sales", description: "Sales automation" },
      { title: "Customer Service", description: "Support management" },
      { title: "Marketing", description: "Marketing automation" },
      { title: "Customization", description: "Tailored solutions" },
    ],
    benefits: [
      "Microsoft ecosystem",
      "Scalable",
      "Integration",
      "Analytics",
    ],
  },
  testing: {
    title: "Software Testing Services",
    subtitle: "Quality Assurance Experts",
    description: "Ensure software quality with our expert testing services. Our QA professionals deliver comprehensive testing for flawless applications.",
    features: [
      { title: "Test Automation", description: "Selenium, Cypress" },
      { title: "Manual Testing", description: "Exploratory testing" },
      { title: "Performance", description: "Load and stress" },
      { title: "Security", description: "Penetration testing" },
    ],
    benefits: [
      "Bug-free releases",
      "Cost savings",
      "Faster time-to-market",
      "User satisfaction",
    ],
  },
  "csharp-mvc": {
    title: "C# / MVC Development",
    subtitle: "Microsoft Web Development",
    description: "Build robust web applications with our C# and ASP.NET MVC experts. Create enterprise-grade applications using Microsoft's proven framework.",
    features: [
      { title: "ASP.NET MVC", description: "Web framework" },
      { title: "Entity Framework", description: "Database access" },
      { title: "Web API", description: "RESTful services" },
      { title: "Identity", description: "Authentication" },
    ],
    benefits: [
      "Enterprise-ready",
      "Strong typing",
      "Visual Studio",
      "Microsoft support",
    ],
  },
};

export const hireList = Object.entries(hireData).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
}));

export const technologyList = Object.entries(technologyData).map(([slug, data]) => ({
  slug,
  title: data.title,
  subtitle: data.subtitle,
}));
